server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_manager
    username: root
    password: Nah1211zz@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
